export const SliderData = [
    {
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROqhGw9ZZnCvG2eQ2X15gPDiCycZBIxgOvGg&usqp=CAU'
    },
    {
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZWrcdBxFUPxyatHy31ry4is4FRt7FdGZDjw&usqp=CAU'
    },
    {
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-qZpo_dgHj3uBJ7t4JKGNoT214DHdT1hKzg&usqp=CAU'
    },
    {
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS26jaHaMummxh7R2defSWOU9VWw2IcLUiljg&usqp=CAU'
    },
    {
      image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOYslFrkdmDrt8Ro53tj1yn2hUYrF7_wJprQ&usqp=CAU'
    }
  ];